apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mockoon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Jix087/mockoon-mx-app-config.git
    targetRevision: HEAD
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mockoon
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    automated:
      selfHeal: true
      prune: true
