#!/usr/bin/env bash
# scripts/generate-configmap.sh
# Generates configmap.yaml from every *.json file in mocks/
# Idempotent — safe to run multiple times.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MOCKS_DIR="$REPO_ROOT/mocks"
OUTPUT="$REPO_ROOT/app/configmap.yaml"

# Compute a combined SHA256 over all mock files (sorted for stability)
CHECKSUM=$(find "$MOCKS_DIR" -name '*.json' | sort | xargs sha256sum | sha256sum | awk '{print $1}')

{
  echo "# Generated by scripts/generate-configmap.sh — do not edit by hand"
  echo "# mocks-checksum: ${CHECKSUM}"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: mockoon-mocks"
  echo "  namespace: mockoon"
  echo "data:"
  for f in $(find "$MOCKS_DIR" -name '*.json' | sort); do
    key="$(basename "$f")"
    echo "  ${key}: |"
    # Indent every line of the JSON with 4 spaces
    sed 's/^/    /' "$f"
  done
} > "$OUTPUT"

echo "Wrote $OUTPUT (checksum: ${CHECKSUM})"

# Stamp the checksum into the Deployment pod-template annotation so ArgoCD
# triggers a rolling restart whenever the ConfigMap content changes.
DEPLOY="$REPO_ROOT/deployment.yaml"
if [[ -f "$DEPLOY" ]]; then
  # Replace the value of the checksum/configmap annotation line in-place.
  sed -i.bak "s|checksum/configmap:.*|checksum/configmap: \"${CHECKSUM}\"|" "$DEPLOY"
  rm -f "$DEPLOY.bak"
  echo "Patched checksum/configmap annotation in $DEPLOY"
fi
